"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuthRouter = void 0;
var express_1 = require("express");
var auth_1 = require("../controllers/auth");
exports.AuthRouter = (0, express_1.Router)();
exports.AuthRouter.post('/register', auth_1.AuthController.register);
exports.AuthRouter.post('/login', auth_1.AuthController.login);
exports.AuthRouter.get('/logout', auth_1.AuthController.logout);
exports.AuthRouter.get('/protected', auth_1.AuthController.protected);
