"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MiListRouter = void 0;
var express_1 = require("express");
var milist_1 = require("../controllers/milist");
exports.MiListRouter = (0, express_1.Router)();
exports.MiListRouter.get('/', milist_1.MiListController.getAll);
exports.MiListRouter.get('/:id', milist_1.MiListController.getByID);
exports.MiListRouter.post('/', milist_1.MiListController.create);
exports.MiListRouter.delete('/:id', milist_1.MiListController.delete);
exports.MiListRouter.put('/:id', milist_1.MiListController.update);
