"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserRouter = void 0;
var express_1 = require("express");
var user_1 = require("../controllers/user");
exports.UserRouter = (0, express_1.Router)();
exports.UserRouter.get('/', user_1.UserController.getAll);
exports.UserRouter.get('/:id', user_1.UserController.getByID);
exports.UserRouter.post('/', user_1.UserController.create);
exports.UserRouter.delete('/:id', user_1.UserController.delete);
exports.UserRouter.put('/:id', user_1.UserController.update);
