"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var NakamaElement_1 = require("./routes/NakamaElement");
var cast_1 = require("./routes/cast");
var metadata_1 = require("./routes/metadata");
var milist_1 = require("./routes/milist");
var query_1 = require("./routes/query");
var rating_1 = require("./routes/rating");
var resource_1 = require("./routes/resource");
var genre_1 = require("./routes/genre");
var credits_1 = require("./routes/credits");
var user_1 = require("./routes/user");
var collection_1 = require("./routes/collection");
var auth_1 = require("./routes/auth");
var api_key_1 = require("./routes/api_key");
var app = (0, express_1.default)();
app.use(express_1.default.json());
app.disable('x-powered-by');
//app.use(AuthMiddleware.verifyAcces)
app.use('/elements', NakamaElement_1.NakamaElementRouter);
app.use('/cast', cast_1.CastRouter);
app.use('/collections', collection_1.CollectionRouter);
app.use('/metadata', metadata_1.MetadataRouter);
app.use('/milist', milist_1.MiListRouter);
app.use('/query', query_1.QueryRouter);
app.use('/rating', rating_1.RatingRouter);
app.use('/resource', resource_1.ResourceRouter);
app.use('/genre', genre_1.GenreRouter);
app.use('/credits', credits_1.CreditsRouter);
app.use('/users', user_1.UserRouter);
app.use('/auth', auth_1.AuthRouter);
app.use('/api_key', api_key_1.ApiKeyRouter);
app.listen(process.env.SERVER_PORT, function () {
    console.log("Server is running on http://localhost:".concat(process.env.SERVER_PORT));
});
